---

- name: Add backport repository
  apt_repository: repo='deb http://mirrors.kernel.org/ubuntu trusty-backports main universe' state=present

- name: Update packages
  apt: update_cache=yes

- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
    - git-core
    - python-argparse
    - python-pip
    - python-dev
    - liberasurecode-dev
