---

- name: Ensure stack user exists
  user: >
      name='stack'
      state=present
      shell=/bin/bash
      groups='sudo'

- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
    - git-core
    - python-argparse
    - python-pip
    - python-dev
