---

- name: Clone devstack
  git: repo=https://github.com/openstack-dev/devstack
       dest=/home/ubuntu/devstack
       version=stable/mitaka

- name: Insert local.conf
  template: >
      src=templates/{{ localconf_filename }}
      dest='/home/ubuntu/devstack/local.conf'
      owner='ubuntu'
      group='ubuntu'

- name: Run stack.sh
  shell: >
      /home/ubuntu/devstack/stack.sh
