---

- hosts: control
  become: yes
  tasks:
  - include: tasks/setup_base.yml

- hosts: control
  tasks:
  - include: tasks/setup_devstack.yml

- hosts: compute
  become: yes
  tasks:
  - include: tasks/setup_base.yml

- hosts: compute
  tasks:
  - include: tasks/setup_devstack.yml

- hosts: block
  become: yes
  tasks:
  - include: tasks/setup_base.yml

- hosts: block
  tasks:
  - include: tasks/setup_devstack.yml
