---

- hosts: controller
  sudo: yes
  sudo_user: 'stack'
  tasks:
  - include: tasks/setup_devstack.yml

- hosts: compute
  sudo: yes
  sudo_user: 'stack'
  tasks:
  - include: tasks/setup_devstack.yml

- hosts: storage
  sudo: yes
  sudo_user: 'stack'
  tasks:
  - include: tasks/setup_devstack.yml
